[package]
name = "ANM_final_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.1"
polars = {version ="0.29.0", features = ["lazy", "interpolate"]}
serde = "1.0.163"
